plugins {
    id 'java'
    id("org.jetbrains.intellij.platform") version "2.18.1"

    id "io.github.ben-manes.versions" version "0.57.0"
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

apply plugin: 'kotlin'
apply plugin: 'idea'

intellijPlatform {
    pluginConfiguration {
        name = plugin_name
    }
    buildSearchableOptions = false
}

dependencies {
    intellijPlatform {
        create("IC", idea_version)
        bundledPlugins(['com.intellij.java'])
    }

    implementation project(':p3c-common')
}

version plugin_version
